### PR TITLE
Feature/enhancement

### PR DESCRIPTION
**Pull request by DeshDeepakKushwaha**
Added Loader while Loading Order
Screenshot 2024-10-08 150251

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the video of whole project.

**Comment by DeshDeepakKushwaha** [comment]
https://github.com/user-attachments/assets/d6a81de3-a02a-45b9-972d-14ce94498254

**Comment by Ayu-hack** [comment]
Great Work !
Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on GitHub and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Pull request merged**
