### PR TITLE
Added solution for Dynamic Menu

### PR DESCRIPTION
**Pull request by pratikj697**
Introduced the Restaurant Management System API, a Flask-based application designed to provide a simple and efficient way to manage restaurant operations. The API enables users to retrieve the menu based on available hours, allowing customers to view the items that can be ordered at any given time.

Features
1. Menu Retrieval: The API endpoint /api/menu fetches menu items that are available during the current hour, enhancing customer experience by providing real-time information.
2. Database Integration: Utilizes MySQL for data storage, allowing easy management of menu items through the menu_item table.
3. Error Handling: Comprehensive error handling for database connectivity issues and queries, ensuring users receive informative messages if something goes wrong.

Database Structure
The following table structure has been implemented:
1. menu_item: Stores information about available menu items.
2. id: INT, auto-incrementing primary key.
3. name: VARCHAR(100), name of the menu item.
4. available_time_start: INT, starting hour during which the item is available (0-23).
5. available_time_end: INT, ending hour during which the item is available (0-23).
6. price: DECIMAL(10,2), price of the menu item.

This project lays the groundwork for a Restaurant Management System, providing a RESTful API that can be further developed to include features such as order management, user authentication, and more.
Screenshot 2024-10-06 193357

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot of working page, to get it merged. 
⭐ Star this repos to get your PR merged faster! 🚀

**Comment by pratikj697** [comment]
> Please share the screenshot of working page, to get it merged.  ⭐ Star this repos to get your PR merged faster! 🚀

Screenshot 2024-10-07 004100
Screenshot 2024-10-07 003713

**Comment by Ayu-hack** [comment]
🎉 Great Work!
Merged. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me** in your Hacktoberfest certificate or badges LinkedIn post! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos to stay updated for next year’s Hacktoberfest!**

**Comment by Ayu-hack** [comment]
brother why you did added python code in React project. I was working on project and I saw your python code file

**Comment by Ayu-hack** [comment]
that day I didn't noticed. I will revert the PR and you to need the changes

**Pull request merged**
