### PR TITLE
Add Navbar and Button

### PR DESCRIPTION
**Pull request by DeshDeepakKushwaha**
Since Separte Menu Page was not looking good so i added a Navbar and format the button for Clearing the Cart
Screenshot 2024-10-07 133703

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please enhance it more nabber is too small.

**Comment by DeshDeepakKushwaha** [comment]
is it good now

https://github.com/user-attachments/assets/2fab8994-9eed-4c1d-b831-d1363653c118

**Comment by Ayu-hack** [comment]
Merged.

**Comment by Ayu-hack** [comment]
in nav bar change MY APP WITH SMART RESTAURANT OR WELCOME

**Pull request merged**
